### ISSUE TITLE
FEATURE

### ISSUE THREAD

**Issue by ATouhou** [Harderer/UnusedCssFinder-Sublime#1]
Hi.  I was thinking of making something like this someday :-) 
A feature I had thought about was prompting the user, to add certain folders to the ignore list, in some kind of GUI, and having standardized folders recommended,  i.e. for projects recognized as a wordpress "fork" limit the search to the themes and plugins folder.  
For frameworks such as CodeIgniter or Laravel, then limit it to only searching in folders that makes sense :-)

**Comment by ATouhou** [comment]
Also when doing the search, then showing some kind of progress bar, instead of just having a "frozen" scren

**Comment by Harderer** [comment]
I have just committed a version with better async code, a progress indicator shows now up at the bottom in sublime and the window won't freeze anymore.
For the other ideas, there is a setting already: 'unused_css_ignore_folders', where you can add all folders, that should be ignored. In this release I also added: 'unused_css_scan_only_folders', where you can specifiy all folders, you only want to scan in a search for occurences. I updated the readme file to communicate these settings.

For the GUI thing: I've never seen any option to configure settings in sublime in a gui. But if you know some reference or example of a gui, I wouldn't hesitate to implement one though. :)

Thanks for sharing your ideas, let me know if you have any more :)

**Comment by ATouhou** [comment]
Actually for the GUI thing I agree xD Only thing I've seen is with dropdowns in the ctrl + p interface (For evernote). Sounds good :P Great work!
