### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NoxNoctis2** [Harderer/UnusedCssFinder-Sublime#2]
Can't make it work with css inside html same as with css in separate file. What am I doing wrong?

![2016-08-02_14-47-53](https://cloud.githubusercontent.com/assets/20794285/17327954/f66ae912-58cb-11e6-8ed6-ad9621e72100.png)

Source:
[index.txt](https://github.com/Harderer/UnusedCssFinder-Sublime/files/396946/index.txt)

**Comment by NoxNoctis2** [comment]
Oh, and could you please add it into Preferences > Package Control >UnusedCssFinder for paranoid people like me.

**Comment by Harderer** [comment]
Thanks for the feedback. Yes it was not intended to be used for inline css before. I've just released a new version, it should work now for these cases. It should have worked with an separate css nevertheless, please check again or I'll try to find out why it wouldn't work.
Also added it to the sublime context menu ;)

**Comment by NoxNoctis2** [comment]
Saparate files in same folder running with fresh release.

![nope_unused_1](https://cloud.githubusercontent.com/assets/20794285/17397498/59c01770-5a49-11e6-97c3-2623d2584d4a.gif)

**Comment by Harderer** [comment]
I just found out, that I forgot to uncomment the examples in the default settings file. I've created a new release with an added debugging option and the corrected default settings file. If the settings file won't override, just uncomment the examples in the settings..
Thanks for informing me again.

**Comment by NoxNoctis2** [comment]
v1.2.1

![2016-08-04_18-35-55](https://cloud.githubusercontent.com/assets/20794285/17408090/e8658c5e-5a7a-11e6-828e-d48a222ccbc6.png)

**Comment by Harderer** [comment]
Yes, the search was not optimal. The declaration was stated as occuring, if the string itself occured in the content. I've optimized the search pattern - it should work now. Thanks for the info.

**Comment by NoxNoctis2** [comment]
It seems to work fine now.

PS: 
Would be great to this features in next releases:
1. Not highlight, but select all unused rules, so we could just press Backspace and... it's cleared.
![select_all](https://cloud.githubusercontent.com/assets/20794285/17511327/79b11f14-5e33-11e6-92c2-8e7351d55053.gif)
1. Define in settings the array of rules that should be excluded from result by deafult.
   If file "unused.cfg" exist in project folder, so default exclusion list should be extended with rules from this file.
   ![default](https://cloud.githubusercontent.com/assets/20794285/17511345/837eb2cc-5e33-11e6-9c93-8cc04120575b.png)
2. Feature "Clear on save"
3. If it's possible, add rules in to project exclude list "on the fly". You just select the rule -> Context menu "Ignore this selector".
   ![ignore_ctxt](https://cloud.githubusercontent.com/assets/20794285/17511694/2fa1e9d8-5e35-11e6-8299-4f9217f00468.png)
